[package]
name = "jxl_decoder"
version = "0.1.1"
authors = ["Google"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
jxl = "0.1.1"
qcms = { path = "../../../gfx/qcms", features = ["c_bindings"] }
xpcom = { path = "../../../xpcom/rust/xpcom" }
nserror = { path = "../../../xpcom/rust/nserror" }
nsstring = { path = "../../../xpcom/rust/nsstring" }
log = "0.4"
libc = "0.2"
